export const blockData = new Map([
  // logs
  ["minecraft:oak_log", { level: 1, item: "minecraft:oak_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:spruce_log", { level: 1, item: "minecraft:spruce_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:birch_log", { level: 1, item: "minecraft:birch_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:jungle_log", { level: 1, item: "minecraft:jungle_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:acacia_log", { level: 1, item: "minecraft:acacia_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:dark_oak_log", { level: 1, item: "minecraft:dark_oak_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:mangrove_log", { level: 1, item: "minecraft:mangrove_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:cherry_log", { level: 1, item: "minecraft:cherry_log", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:crimson_stem", { level: 1, item: "minecraft:crimson_stem", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:warped_stem", { level: 1, item: "minecraft:warped_stem", itemPerLevel: 1, chance: 0.33 }],
  // ores
  ["minecraft:coal_ore", { level: 1, item: "minecraft:coal", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:deepslate_coal_ore", { level: 1, item: "minecraft:coal", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:copper_ore", { level: 1, item: "minecraft:raw_copper", itemPerLevel: 5, chance: 0.33 }],
  ["minecraft:deepslate_copper_ore", { level: 1, item: "minecraft:raw_copper", itemPerLevel: 5, chance: 0.33 }],
  ["minecraft:iron_ore", { level: 2, item: "minecraft:raw_iron", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:deepslate_iron_ore", { level: 2, item: "minecraft:raw_iron", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:gold_ore", { level: 3, item: "minecraft:raw_gold", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:deepslate_gold_ore", { level: 3, item: "minecraft:raw_gold", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:redstone_ore", { level: 2, item: "minecraft:redstone", itemPerLevel: 9, chance: 0.33 }],
  ["minecraft:deepslate_redstone_ore", { level: 2, item: "minecraft:redstone", itemPerLevel: 9, chance: 0.33 }],
  ["minecraft:lapis_ore", { level: 2, item: "minecraft:lapis_lazuli", itemPerLevel: 9, chance: 0.33 }],
  ["minecraft:deepslate_lapis_ore", { level: 2, item: "minecraft:lapis_lazuli", itemPerLevel: 9, chance: 0.33 }],
  ["minecraft:diamond_ore", { level: 3, item: "minecraft:diamond", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:deepslate_diamond_ore", { level: 3, item: "minecraft:diamond", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:emerald_ore", { level: 3, item: "minecraft:emerald", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:deepslate_emerald_ore", { level: 3, item: "minecraft:emerald", itemPerLevel: 1, chance: 0.33 }],
  ["minecraft:nether_gold_ore", { level: 2, item: "minecraft:gold_nugget", itemPerLevel: 6, chance: 0.33 }],
  ["minecraft:quartz_ore", { level: 2, item: "minecraft:quartz", itemPerLevel: 1, chance: 0.33 }],
]);
