execute @e[r=6,type=minecraft:item] ~ ~ ~ tag @s add tc:previous

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_iron_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ clay -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ gravel -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ copper_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ nether_gold_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_emerald_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ ancient_debris -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ lapis_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_lapis_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ redstone_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ lit_deepslate_redstone_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ lit_redstone_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_copper_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_gold_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ gold_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ iron_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ emerald_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ diamond_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ minecraft:deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_diamond_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ coal_ore -1 setblock ~ ~ ~ air 0 destroy

execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~ ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~ ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~ ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~ ~-1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~1 ~-1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~ detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy
execute @e[r=6,type=minecraft:item,tag=!tc:done] ~-1 ~-1 ~-1 detect ~ ~ ~ deepslate_coal_ore -1 setblock ~ ~ ~ air 0 destroy